num = int(input('Digite um numero de 0 a 9999: '))
unidade = num // 1 % 10
dezena = num  // 10 % 10
centena = num // 100 % 10
milhar = num // 1000 % 10 
print(f'Unidade = {unidade}')
print(f'Dezena =  {dezena}')
print(f'Centena = {centena}')
print(f'Milhar = {milhar}')