nome = input('Digite seu nome inteiro: ').strip()
maiuscula = nome.upper()
minuscula = nome.lower()
caracteres = len(nome) - nome.count(' ')
separacao = nome.split()
print(f'Maiusculas: {maiuscula}')
print(f'Minusculas: {minuscula}')
print(f'Total sem espaço: {caracteres}')
print(f'Total de letras primeiro nome: {len(separacao[0])}')